### ISSUE TITLE
Some ligatures are not working

### ISSUE THREAD

**Issue by sirxemic** [RoelN/SansBullshitSans#10]
The ligature for "usercentric" does not work because the substring "user" already has a ligature.
Same story for "lean"/"lean in" and "social media"/"social media expert".

See: http://i.imgur.com/OvSkKie.png

**Comment by RoelN** [comment]
Yep, known issue. I'm keeping https://github.com/RoelN/SansBullshitSans/issues/13 open in case there's a solution.
