### ISSUE TITLE
[FEATURE] Regular expression support for better bullshit support

### ISSUE THREAD

**Issue by jinnovation** [RoelN/SansBullshitSans#12]
Might be a bit of a stretch given how bullshit's currently detected, but regex support would allow detection of stuff like the following:
- "the <company name> for <bullshit>"
- "like <company name>, but <bullshit>"

**Comment by RoelN** [comment]
Unfortunately, the OpenType GSUB table doesn't support regexes. Maybe if you'd really, really abuse contextual ligatures...
