### ISSUE TITLE
How is this font created?

### ISSUE THREAD

**Issue by DonaldTsang** [RoelN/SansBullshitSans#32]
Was wondering how this works, and if I can add or subtract words from the font.

**Comment by DonaldTsang** [comment]
Adding some other references, since they all try to do similar things.
- http://projectseen.com/
- https://www.thepolitetype.com/
- https://vole.wtf/scunthorpe-sans/

**Comment by RoelN** [comment]
Explanation on how this font was built: http://pixelambacht.nl/2015/sans-bullshit-sans/
